### ISSUE TITLE
No argument need proof too

### ISSUE THREAD

**Issue by Siegerz** [TheCuteOwl/Trap-Stealer#13]

**Comment by TheCuteOwl** [comment]
Argument please

**Comment by Siegerz** [comment]
i Think That Sentence Made You Abit Retarded,

**Comment by Siegerz** [comment]
Your White Blood Cells Committed Suicide When You Were Six Due To The Fact That Your Singapore Dad Gaped Your Asshole And Hit It From The Back

**Comment by TheCuteOwl** [comment]
if you say so ig

**Comment by TheCuteOwl** [comment]
You know spamming and insulting is funny?

**Comment by Siegerz** [comment]
Cant Wait To See You On Live Leak Injecting Adderall And Kamagra Straight Into Your Oesophagus You Fucking Freakanature Abomination Fucking Freak

**Comment by Siegerz** [comment]
Amazin

**Comment by TheCuteOwl** [comment]
If you say so
