### ISSUE TITLE
Bot

### ISSUE THREAD

**Issue by Siegerz** [TheCuteOwl/Trap-Stealer#14]

**Comment by TheCuteOwl** [comment]
I am not

**Comment by Azuuu1** [comment]
bro what u talking abt u litteraly have a rat in your repository shut the fuck up ur father selled u in a zoo as a monkey they said ur too fat what u talking abt ur so blind that when u tryed sucking my dick u sucked my balls get off my dick stop dickriding buddy

**Comment by TheCuteOwl** [comment]
First of all, give proof, you are just lying and then for the end of your sentence i like to do that

**Comment by TheCuteOwl** [comment]
imagine ur alt got banned haha
