### ISSUE TITLE
Hi :)

### ISSUE THREAD

**Issue by m1daz** [TheCuteOwl/Trap-Stealer#16]
https://github.com/applebytez/blank-fucker

you're next.

**Comment by m1daz** [comment]
it may interest you as in why blank-c closed down his project :), you know, the guy whose obfuscator you pasted.

**Comment by TheCuteOwl** [comment]
Yes, have fun

**Comment by TheCuteOwl** [comment]
still waiting btw

**Comment by TheCuteOwl** [comment]
i'm bored, please

**Comment by TheCuteOwl** [comment]
are u even here?
