### ISSUE TITLE
Nuitka

### ISSUE THREAD

**Issue by furax124** [TheCuteOwl/Trap-Stealer#18]
Compile with nuitka and clean some code it's ugly.

**Comment by TheCuteOwl** [comment]
Why would i care its still fast and compile it yourself

**Comment by furax124** [comment]
> Why would i care its still fast and compile it yourself

Because it's easy to decompile it your code is fucking ugly

**Comment by TheCuteOwl** [comment]
Well make an better obfuscator and make the code look better :3

**Comment by furax124** [comment]
> Well make an better obfuscator and make the code look better :3

It's always be an archive with pyinstaller dumbass do whatever obfuscation you want we can Easily decompile it and deobfuscate it because it's a interpreted language take a fucking good language take a compiled language nuitka can do that but you are so dumb do just change a fucking module

**Comment by TheCuteOwl** [comment]
I will not, useless, this type of script is normally make to be into a infected pypi package not a exe, so useless to compile it to exe, and nuitka

**Comment by furax124** [comment]
> I will not, useless, this type of script is normally make to be into a infected pypi package not a exe, so useless to compile it to exe, and nuitka

I'm not gonna say something cause you are to dumb to understand
