### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by ZadgeIsCool** [TheCuteOwl/Trap-Stealer#2]
"Camera screen cannot be taken" and it doesnt generate the "Trap Stealer Zips" or the cookies or the passwords. the only proper thing it generates is "email" and "phone" and "discord token". also the "billing" doesnt generate. please fix ty <3

**Comment by TheCuteOwl** [comment]
Camera screen cannot be taken : Have you a camera? 

And can you send a screen on how it look like ?

**Comment by TheCuteOwl** [comment]
Is there any error?

**Comment by TheCuteOwl** [comment]
Hi dear i found the problem, it was about thread because it didnt check if everything was good or not

**Comment by TheCuteOwl** [comment]
A fixed version have been uploaded tell me if you got another problem ^^

**Comment by ZadgeIsCool** [comment]
> A fixed version have been uploaded tell me if you got another problem ^^

i will tell u soon but can u make it FUD exe?

**Comment by ZadgeIsCool** [comment]
> A fixed version have been uploaded tell me if you got another problem ^^

Exception in thread Thread-3 (upload_files_to_discord):
Traceback (most recent call last):
  File "C:\Users\zadge\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\zadge\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "Modi-Fuscate", line 803, in upload_files_to_discord
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\zadge/Pictures'

**Comment by ZadgeIsCool** [comment]
I tried in a VM (with no Anti-VM) and it did nothing.

**Comment by TheCuteOwl** [comment]
Yes sorry for the antivm it dont work but it's useless xD (i will fix it later)
and new update

**Comment by ZadgeIsCool** [comment]
ok

**Comment by ZadgeIsCool** [comment]
File "C:\Users\zadge\OneDrive\Pictures\Trap-Stealer-main\main.py", line 843
    def ZipTelegram(path, arg, procc):
SyntaxError: expected 'except' or 'finally' block

**Comment by TheCuteOwl** [comment]
Sorry i forgot an except ahah, fixed

**Comment by ZadgeIsCool** [comment]
ok thanks

**Comment by ZadgeIsCool** [comment]
when i open main.py it does nothing

**Comment by TheCuteOwl** [comment]
Maybe add a webhook

**Comment by TheCuteOwl** [comment]
and dont touch main, and use the builder

**Comment by ZadgeIsCool** [comment]
ok

**Comment by ZadgeIsCool** [comment]
Trap-Stl-Builted-Obf.py does nothing

**Comment by TheCuteOwl** [comment]
have you put the webhook with the builder (an working one) or try the non obfuscated one

**Comment by ZadgeIsCool** [comment]
i put the webhook

**Comment by ZadgeIsCool** [comment]
no obfuscated works

**Comment by TheCuteOwl** [comment]
it work well?

**Comment by TheCuteOwl** [comment]
How strong have you obfuscated it?

**Comment by ZadgeIsCool** [comment]
wait

**Comment by ZadgeIsCool** [comment]
no

**Comment by ZadgeIsCool** [comment]
camera doesnt get grabbed

**Comment by ZadgeIsCool** [comment]
zips doesnt generate

**Comment by TheCuteOwl** [comment]
Do you have a camera xD

**Comment by ZadgeIsCool** [comment]
everything doesnt work

**Comment by TheCuteOwl** [comment]
game zip too? every zip?

**Comment by TheCuteOwl** [comment]
can you tell me what you get on the non obfuscated one?

**Comment by ZadgeIsCool** [comment]
obfuscated doesnt work

**Comment by ZadgeIsCool** [comment]
100

**Comment by ZadgeIsCool** [comment]
email and phone and token

**Comment by TheCuteOwl** [comment]
hmm what windows are you using?

**Comment by ZadgeIsCool** [comment]
only that

**Comment by ZadgeIsCool** [comment]
i run the program in windows 11

**Comment by ZadgeIsCool** [comment]
i get information in VM windows 10

**Comment by TheCuteOwl** [comment]
try to launch it on windows 10

**Comment by ZadgeIsCool** [comment]
i did

**Comment by ZadgeIsCool** [comment]
Wait

**Comment by ZadgeIsCool** [comment]
unobfuscated VMWare windows 10 builder.py right?

**Comment by TheCuteOwl** [comment]
ye

**Comment by TheCuteOwl** [comment]
are you using a vm win10? or 11?

**Comment by ZadgeIsCool** [comment]
VM win10

**Comment by ZadgeIsCool** [comment]
real win11

**Comment by TheCuteOwl** [comment]
So you run the program on the vm win10 or real 11?

**Comment by ZadgeIsCool** [comment]
vm win10

**Comment by TheCuteOwl** [comment]
could you try real 11?

**Comment by TheCuteOwl** [comment]
why completed?

**Comment by ZadgeIsCool** [comment]
what?

**Comment by TheCuteOwl** [comment]
@[ZadgeIsCool](https://github.com/ZadgeIsCool) ZadgeIsCool closed this as [completed](https://github.com/TheCuteOwl/Trap-Stealer/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [now](https://github.com/TheCuteOwl/Trap-Stealer/issues/2#event-9791602043)

**Comment by TheCuteOwl** [comment]
and can you try launching it on your real computer without vm

**Comment by ZadgeIsCool** [comment]
No

**Comment by TheCuteOwl** [comment]
maybe it would work

**Comment by ZadgeIsCool** [comment]
I tried this on Real win11

**Comment by ZadgeIsCool** [comment]
doesnt work

**Comment by TheCuteOwl** [comment]
humm strange

**Comment by ZadgeIsCool** [comment]
it works but

**Comment by ZadgeIsCool** [comment]
no camera no zip

**Comment by ZadgeIsCool** [comment]
only email and phone and discord token

**Comment by TheCuteOwl** [comment]
hmm strange

**Comment by ZadgeIsCool** [comment]
when i try to run in vm win10 i have discord but it doesnt take my email or phone or token

**Comment by TheCuteOwl** [comment]
can you show me the config ? at the top

**Comment by ZadgeIsCool** [comment]
builder py?

**Comment by ZadgeIsCool** [comment]
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/34542867/cdbedc37-07b3-4a9f-affe-ec424ad4b159)

**Comment by TheCuteOwl** [comment]
Nono at the top of the non obfuscated built

**Comment by ZadgeIsCool** [comment]
ok

**Comment by TheCuteOwl** [comment]
show me

**Comment by ZadgeIsCool** [comment]
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/34542867/67afe7dc-a5da-496b-9b53-4a0dfa1349fd)

**Comment by TheCuteOwl** [comment]
everything seem right...

Can you try to put multiple print near line 1210 just to check if it still right or if it stop at some point

**Comment by ZadgeIsCool** [comment]
1 min

**Comment by ZadgeIsCool** [comment]
sorry

**Comment by ZadgeIsCool** [comment]
what do i do?

**Comment by TheCuteOwl** [comment]
put some print at the line 1210, to check if something happen or not and then launch it and tell me if it is print

**Comment by ZadgeIsCool** [comment]
so i put "print" at line 1210?

**Comment by TheCuteOwl** [comment]
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/114611129/94f9966c-8c9c-4fdc-9059-38899c5f12db)

**Comment by TheCuteOwl** [comment]
Do thiung like that

**Comment by TheCuteOwl** [comment]
maybe i know the problem , but just wanna check

**Comment by ZadgeIsCool** [comment]
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/34542867/356b7535-5bea-439f-be03-8135f3d9f08e)

**Comment by TheCuteOwl** [comment]
why print doesnt work ahah

**Comment by TheCuteOwl** [comment]
have you install python on vs code?

**Comment by TheCuteOwl** [comment]
just save even if there is error and just launch it

**Comment by ZadgeIsCool** [comment]
ok

**Comment by TheCuteOwl** [comment]
Oh you put in in the wrong thing put it near line 1210

**Comment by TheCuteOwl** [comment]
you put it under line 1100

**Comment by ZadgeIsCool** [comment]
bru

**Comment by TheCuteOwl** [comment]
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/114611129/cf88e5e2-8d8a-43c4-a9c0-c6bef2231338)
you put it here

**Comment by TheCuteOwl** [comment]
put it here

**Comment by ZadgeIsCool** [comment]
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/34542867/c6f23147-cc52-470d-a33a-bb96307316f2)

**Comment by ZadgeIsCool** [comment]
it says 1210

**Comment by TheCuteOwl** [comment]
wait wut

**Comment by TheCuteOwl** [comment]
download the latest main.py because there is a problem '-'

**Comment by TheCuteOwl** [comment]
How did you get +100 line '-'

**Comment by ZadgeIsCool** [comment]
I have latest main.py

**Comment by TheCuteOwl** [comment]
show the last line of the file?

**Comment by ZadgeIsCool** [comment]
GatherAll()

**Comment by ZadgeIsCool** [comment]
1357

**Comment by TheCuteOwl** [comment]
HOW wait

**Comment by TheCuteOwl** [comment]
https://pastebin.com/Ppxs3ucY

**Comment by TheCuteOwl** [comment]
take this fixed version

**Comment by ZadgeIsCool** [comment]
BRO

**Comment by TheCuteOwl** [comment]
what?

**Comment by ZadgeIsCool** [comment]
when i paste it in pycharm it shows 1357 last line

**Comment by ZadgeIsCool** [comment]
how

**Comment by TheCuteOwl** [comment]
BRUH
xD

**Comment by ZadgeIsCool** [comment]
vs code works good

**Comment by TheCuteOwl** [comment]
try to make a txt file, put the code in it, and saved it at main.py

**Comment by TheCuteOwl** [comment]
try to launch it with it

**Comment by ZadgeIsCool** [comment]
ok done

**Comment by TheCuteOwl** [comment]
it work ?

**Comment by ZadgeIsCool** [comment]
IT DOES NOTHING SBUGHGSIBUGHIS

**Comment by TheCuteOwl** [comment]
zsehifghuoe

**Comment by TheCuteOwl** [comment]
have you used the builder?

**Comment by ZadgeIsCool** [comment]
wait no

**Comment by ZadgeIsCool** [comment]
YES

**Comment by ZadgeIsCool** [comment]
BUT STILL

**Comment by ZadgeIsCool** [comment]
CAMERA BROKEN

**Comment by ZadgeIsCool** [comment]
AND ZIPS

**Comment by ZadgeIsCool** [comment]
only generates discord token and email and phone

**Comment by ZadgeIsCool** [comment]
do you have discord?

**Comment by TheCuteOwl** [comment]
can you show me what it send to discord? with a screen (censored stuff)

**Comment by ZadgeIsCool** [comment]
can you friend me in discord? zadge2

**Comment by TheCuteOwl** [comment]
@felix.argyle.

**Comment by ZadgeIsCool** [comment]
@TheCuteOwl
