### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by RootFungus** [TheCuteOwl/Trap-Stealer#21]
![error](https://github.com/TheCuteOwl/Trap-Stealer/assets/101245783/14b82253-2e14-4d79-a2a9-f3c4d9103828)
it used to work but now when i launch the build it doesnt send any info the cmd prompt opens and immediately closes

**Comment by RootFungus** [comment]
FIXED

**Comment by TheCuteOwl** [comment]
Well xD
