### ISSUE TITLE
Not working again

### ISSUE THREAD

**Issue by RootFungus** [TheCuteOwl/Trap-Stealer#23]
i finish the build and when i launch it cmd prompt opens for a sec and closes cant even see whats written on there

edit: got the screenshot
![Screenshot 2023-09-26 000848](https://github.com/TheCuteOwl/Trap-Stealer/assets/101245783/535cbe64-f0c5-4952-9f19-04d21522a0cf)

edit 2: got it to work and send the info however it gives this error 
![Screenshot 2023-09-26 013434](https://github.com/TheCuteOwl/Trap-Stealer/assets/101245783/00942a53-2865-421f-98c6-f9c37103b848)

**Comment by TheCuteOwl** [comment]
let me try to fix i know where it is from

**Comment by TheCuteOwl** [comment]
Fixed let me know if they are any more error like that
