### ISSUE TITLE
again

### ISSUE THREAD

**Issue by RootFungus** [TheCuteOwl/Trap-Stealer#24]
i dont know if im the only one having issues but the build works perfectly on my laptop but when i try to launch it on my other computers it opens and closes in a sec

**Comment by TheCuteOwl** [comment]
Please
what is the error showned on the other computer

**Comment by TheCuteOwl** [comment]
Show the bug

**Comment by RootFungus** [comment]
> Please what is the error showned on the other computer

nothing it immediatelly closed

**Comment by TheCuteOwl** [comment]
With an error open it with cmd and then Drag the file into the cmd

**Comment by TheCuteOwl** [comment]
have you downloaded the latest version?

**Comment by RootFungus** [comment]
> have you downloaded the latest version?

yes

**Comment by TheCuteOwl** [comment]
i could give you a new obfuscation that may work

**Comment by RootFungus** [comment]
> wait do you have discord?

ogshady666

**Comment by TheCuteOwl** [comment]
thanks i'll add you soon !

**Comment by RootFungus** [comment]
Thank you
