### ISSUE TITLE
Startup request to exe 

### ISSUE THREAD

**Issue by Usman2khan** [TheCuteOwl/Trap-Stealer#28]
the startup file is saving as .pyw it want run in the system which doesn't  have python the current exe file would be better it will be great if it is the current .exe file

**Comment by TheCuteOwl** [comment]
Added

**Comment by Usman2khan** [comment]
![Screenshot](https://github.com/TheCuteOwl/Trap-Stealer/assets/119128617/74f49185-fcb6-481c-beab-694c0a9df84e)
The .exe is not executing in startup

**Comment by TheCuteOwl** [comment]
I know why, please wait

**Comment by TheCuteOwl** [comment]
new update
