### ISSUE TITLE
How cute

### ISSUE THREAD

**Issue by Napoleon-x** [TheCuteOwl/Trap-Stealer#3]
This project is rather underrated and seems pretty cool, keep up the good work python femboy!
Although I think you could add more stuff related to Firefox, a fun hint on the fun stuff you can do, have a look at the nss3.dll within Firefox directory, you can do lots of cool stuff with that! You should link a discord idk

**Comment by rumor1337** [comment]
sir of napoleon i am fossos message me now "eextend" I want to ask you a few questions NOW

**Comment by TheCuteOwl** [comment]
Hi dear first of all thanks ^^

 i will look at what i can do with firefox, 

and for discord
i will give it when i wake up ^^ i dont really wanna put a public discord server or put my discord publicly so i dont have a lot of Friend request (sorry for my Bad english)

**Comment by TheCuteOwl** [comment]
felix.argyle.

**Comment by TheCuteOwl** [comment]
that my discord
