### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Usman2khan** [TheCuteOwl/Trap-Stealer#30]
![Screenshot](https://github.com/TheCuteOwl/Trap-Stealer/assets/119128617/dc0d742b-3eca-4bb5-a563-3fb810e4c19d)
The Stealer is working fine but this is the error and it doesn't make any filr or .exe in the startup

**Comment by TheCuteOwl** [comment]
is the file appeared in startup?

**Comment by Usman2khan** [comment]
No

**Comment by TheCuteOwl** [comment]
Okay gonna work on a fix

**Comment by TheCuteOwl** [comment]
updated

**Comment by Usman2khan** [comment]
Still the same error

**Comment by TheCuteOwl** [comment]
new update

**Comment by TheCuteOwl** [comment]
fixed
