### ISSUE TITLE
Virus Detected

### ISSUE THREAD

**Issue by Usman2khan** [TheCuteOwl/Trap-Stealer#31]
Hey Why are you using pyinstaller it is detected as virus please use nuitka for building .exe

**Comment by TheCuteOwl** [comment]
it is detected as much

**Comment by TheCuteOwl** [comment]
build it using nuitka and show me how many detection

**Comment by Usman2khan** [comment]
but when i use nuitka the put in startup is not working no file is being added in the startup

**Comment by TheCuteOwl** [comment]
that the problem, nuitka is a lot different, i don't think i'll change it for now

**Comment by Usman2khan** [comment]
Okay

**Comment by TheCuteOwl** [comment]
Can i close?

**Comment by Usman2khan** [comment]
sure

**Comment by TheCuteOwl** [comment]
have a nice day
