### ISSUE TITLE
Its not FUD Virus Detected 

### ISSUE THREAD

**Issue by Usman2khan** [TheCuteOwl/Trap-Stealer#32]
![Screenshot (25)](https://github.com/TheCuteOwl/Trap-Stealer/assets/119128617/37a2246d-3012-44cd-b349-0a69f750ba30)
![Screenshot (26)](https://github.com/TheCuteOwl/Trap-Stealer/assets/119128617/a795900e-c9d2-42f8-bc8b-8e2c8969e085)

When i run the exe its shows the pop up that process terminated and when i check the report as mentioned its been catch by system watcher by checking the behavior of the program

**Comment by TheCuteOwl** [comment]
Python FUD not Exe

**Comment by githubianuser** [comment]
get a good crypter lil man
