### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MrShadowDev** [TheCuteOwl/Trap-Stealer#33]
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/71973368/fabb1cb9-ee38-43ff-8ee5-b4d90c9166c9)
Links not showing

**Comment by TheCuteOwl** [comment]
Where have you launched it? vm?

**Comment by MrShadowDev** [comment]
> Where have you launched it? vm?

nope its the pc of victim

**Comment by TheCuteOwl** [comment]
Have you scanned it using virus total? just to know

**Comment by MrShadowDev** [comment]
> Have you scanned it using virus total? just to know

yes and sent with link but victim nope

**Comment by TheCuteOwl** [comment]
If you scan it on virus total it may be the VM, is the windows version Entreprise or Pro?

**Comment by MrShadowDev** [comment]
Product name : Windows 10 Pro

**Comment by TheCuteOwl** [comment]
It may be the vm that launched it, not the victim

**Comment by MrShadowDev** [comment]
now got linksttold the to victim to execute it again

**Comment by TheCuteOwl** [comment]
haha have a nice day
