### ISSUE TITLE
cant seem to figure out how to build the exe

### ISSUE THREAD

**Issue by AnimeKally** [TheCuteOwl/Trap-Stealer#35]

**Comment by TheCuteOwl** [comment]
use the builder.py

**Comment by AnimeKally** [comment]
> use the builder.py

its a py... who exactly do I run the .py?

**Comment by TheCuteOwl** [comment]
what? just install python

**Comment by AnimeKally** [comment]
what do I even do after downloading python 
???

**Comment by TheCuteOwl** [comment]
start builder.py
