### ISSUE TITLE
Cookie Grabber error

### ISSUE THREAD

**Issue by Slypoof** [TheCuteOwl/Trap-Stealer#40]
![Screenshot_2024-01-07-20-23-41-29](https://github.com/TheCuteOwl/Trap-Stealer/assets/155521109/852efb40-e92d-4c30-ace6-dee3e315e512)

**Comment by TheCuteOwl** [comment]
Did you launched it on yourself?
Did google was launched?

**Comment by Slypoof** [comment]
Launched by a friend and yes

**Comment by Slypoof** [comment]
When launched again it didnt get his roblox cookie even though he is clearly logged in google chrome

**Comment by TheCuteOwl** [comment]
Okay tell him to close chrome

**Comment by TheCuteOwl** [comment]
and start it again

**Comment by Slypoof** [comment]
still same result

**Comment by TheCuteOwl** [comment]
hummm

**Comment by TheCuteOwl** [comment]
do you have any error or nothing?

**Comment by Slypoof** [comment]
No, just the cookie

**Comment by Slypoof** [comment]
The other features works fine

**Comment by TheCuteOwl** [comment]
Okkay thanks imma work on it

**Comment by Slypoof** [comment]
Okay, looki

**Comment by TheCuteOwl** [comment]
wait
what are the options u've enabled when building it?

**Comment by TheCuteOwl** [comment]
Fixed!
