### ISSUE TITLE
Where are my credits?

### ISSUE THREAD

**Issue by JunkieOpfer** [TheCuteOwl/Trap-Stealer#41]
you use my injection but there are no credits 

![Screenshot 2024-01-07 202646](https://github.com/TheCuteOwl/Trap-Stealer/assets/142160147/f453fc99-3750-44d8-9aa7-544e9eb08dd9)

**Comment by TheCuteOwl** [comment]
Send me chat github url

**Comment by TheCuteOwl** [comment]
I want to check something

**Comment by TheCuteOwl** [comment]
Because afterall i didnt used ur injection, i've changed to Doenerium one so not yours

**Comment by JunkieOpfer** [comment]
https://github.com/JunkieOpfer/star/issues/1#issuecomment-1880145331

last month i changed the repo to privat but here

**Comment by TheCuteOwl** [comment]
can't see it, but ye i dont use ur injection
