### ISSUE TITLE
Not FUD 24/69 Detections

### ISSUE THREAD

**Issue by Inplex-sys** [TheCuteOwl/Trap-Stealer#42]

**Comment by TheCuteOwl** [comment]
Hi dear, it is python FUD i never talked about exe FUD, I'm working on a way to get 3/69

**Comment by Inplex-sys** [comment]
I see, but having a FUD python file and Fully Detectable exe seems useless

**Comment by TheCuteOwl** [comment]
I've updated it now there is an alternative way that give 5/69 detections (all of them are all false positive)

**Comment by Inplex-sys** [comment]
false positive ?
