### ISSUE TITLE
Cant download files

### ISSUE THREAD

**Issue by mr-cat-sudo** [TheCuteOwl/Trap-Stealer#43]
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/71202514/12b5896a-a209-4462-a245-4558ce5fa91b)

**Comment by TheCuteOwl** [comment]
Use another file services and tell me which one os it ?

**Comment by TheCuteOwl** [comment]
FIXED

**Comment by mr-cat-sudo** [comment]
ty
