### ISSUE TITLE
someone has stolen your grabber and dual hooked it and is giving it out: https://discord.gg/ZRm5ehDgar how has he done it?

### ISSUE THREAD

**Issue by AnimeKally** [TheCuteOwl/Trap-Stealer#47]

**Comment by TheCuteOwl** [comment]
Hi, thanks for letting me know, sadly my program is open sources and easiliy modifiable

**Comment by AnimeKally** [comment]
idk why but the guy deleted the serv i know bc I didn't get any msg from discord (u were in a serv which supports) i didn't get it so the guy took it down himself

**Comment by TheCuteOwl** [comment]
Yes, I think so, I've talked to him, and i've proved that It was dualhooked
