### ISSUE TITLE
I only get token no files

### ISSUE THREAD

**Issue by Helden1pro** [TheCuteOwl/Trap-Stealer#49]
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/117112323/a190ffbf-e328-439d-ab6f-d084687492e1)

**Comment by TheCuteOwl** [comment]
Can't do that much, need error if you can get it

**Comment by Helden1pro** [comment]
wym u mean that fake error code

**Comment by Helden1pro** [comment]
if you mean that when i got it i still didn't get anything i followed the tutorial in the dc server

**Comment by TheCuteOwl** [comment]
No, I need to get the error that is sent by the code, I can't fix it if I dont know hwere the error is

**Comment by TheCuteOwl** [comment]
and it may be, because he closes it

**Comment by Helden1pro** [comment]
still doesnt work

**Comment by dankor33** [comment]
send error or enable debug mode and send txt

**Comment by Helden1pro** [comment]
tried it again does work now 
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/117112323/7ef13536-294b-40f6-9057-b111b23f7e03)

**Comment by TheCuteOwl** [comment]
xD
