### ISSUE TITLE
Iban_Stealer is not defined 

### ISSUE THREAD

**Issue by dankor33** [TheCuteOwl/Trap-Stealer#58]
its not defined this my way how I fixed it
https://github.com/dankor33/TrapStealerPacked/blob/main/builder.py#LL137

**Comment by TheCuteOwl** [comment]
Fixed in the newest update

**Comment by dankor33** [comment]
> Fixed in the newest update

still broken 😢

**Comment by TheCuteOwl** [comment]
Fixed now
