### ISSUE TITLE
dude why

### ISSUE THREAD

**Issue by Azuuu1** [TheCuteOwl/Trap-Stealer#60]
hey cute owl idk if u remember me or not we were kind off friends we were wanting to make a stealer together called "Moon grabber" well that project got abandoned but not about that i wanted to talk to u but since u deleted ur discord theres really no way to contact u so im trying here i need help with python and ur the only person i know that was willing to help me and yeah i kinda miss talkin to u cuz u were cool and all that so yeah

**Comment by TheCuteOwl** [comment]
Sorry, if you need help i'm still here, but i wont talk on something else as giothub

**Comment by Azuuu1** [comment]
> Sorry, if you need help i'm still here, but i wont talk on something else as giothub

well cant u make a discord please i have an important thing
