### ISSUE TITLE
Not working right

### ISSUE THREAD

**Issue by XesUl** [TheCuteOwl/Trap-Stealer#63]
I tried it on myself, and after running the .exe file, some things happened. I managed to get some stuff into my DC, but not everything. Only the Python version works somewhat correctly, and even then, it's sporadic. Sometimes it sends information about the device, sometimes it also includes information about other login credentials, and sometimes nothing at all. It's kind of random.

And I get the error only at the exe file. Kinda weird, cause at the end i get not rlly any Infos.

Edit: Now it doesnt wanna work at all... so confused and dont get it. I got this now:
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/49734839/a5e32b06-3087-468e-a353-0fc7946033f5)

But the other message is missing. 
![image](https://github.com/TheCuteOwl/Trap-Stealer/assets/49734839/dcdc1002-595b-4916-9ca2-a2d9f3bac7f9)

Its right how I use it? Download Zip -> Extracting -> install requirements.txt -> run builder.py -> choose what i want -> say EXE file at the end -> pythoninstaller or how to create the exe -> finished = run .exe file to test it. Then it should send all Infos to my dc webhook.

**Comment by TheCuteOwl** [comment]
I would need more than that , to help a bit, keep in mind, the project is stopped i won't update it, but if youi want to know don't use pyinstaller use the other thing
